require 'simplecov'
require 'minitest/pride'
SimpleCov.start do
  add_filter 'test/'
  add_filter 'lib/day_of_week'
end

require_relative 'item_repo_test'
require_relative 'item_test'
require_relative 'merchant_repo_test'
require_relative 'merchant_test'
require_relative 'sales_engine_test'
require_relative 'sales_analyst_test'
require_relative 'invoice_repo_test'
require_relative 'invoice_test'
require_relative 'invoice_item_repo_test'
require_relative 'invoice_item_test'
require_relative 'customer_test'
require_relative 'customer_repo_test'
require_relative 'transaction_test'
require_relative 'transaction_repo_test'
